# Generated by Django 6.0.5 on 2026-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('linkedin', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('cgpa', models.CharField(max_length=20)),
                ('passing_year', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('projects', models.TextField()),
                ('experience', models.TextField()),
                ('certifications', models.TextField()),
                ('achievements', models.TextField()),
                ('languages', models.CharField(max_length=200)),
            ],
        ),
    ]
